# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 13:11
from __future__ import unicode_literals

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=django_countries.fields.CountryField(default='PA', max_length=2, verbose_name='Country'),
            preserve_default=False,
        ),
    ]
