# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-25 22:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0010_auto_20160925_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='members',
            field=models.ManyToManyField(related_name='organizations', to=settings.AUTH_USER_MODEL, verbose_name='Members'),
        ),
    ]
