# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 13:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0011_auto_20160925_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wildbillsprofile',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='wildbillsprofile',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='WildBillsProfile',
        ),
    ]
